// <auto-generated />
namespace Task5.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_SP_ClientOrdersCost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_SP_ClientOrdersCost));
        
        string IMigrationMetadata.Id
        {
            get { return "201710100623116_Add_SP_ClientOrdersCost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
